### ISSUE TITLE
[BUG] TypeError: Cannot read properties of undefined (reading 'customId')

### ISSUE THREAD

**Issue by GlxryX** [acegoal07/discordjs-pagination#11]
**Describe the bug**
Pagination buttons do not work

**Error message**
```TypeError: Cannot read properties of undefined (reading 'customId')```

**Sample of the code where it is used**
```js
new paginationWrapper()
.setInteraction(interaction)
.setPageList(pageList)
.setButtonList([
  new Discord.ButtonBuilder()
    .setCustomId('firstbtn')
    .setEmoji({ id: '959992408433627137' })
    .setStyle('Secondary'),
  new Discord.ButtonBuilder()
    .setCustomId('previousbtn')
    .setEmoji({ id: '924719153288458271' })
    .setStyle('Secondary'),
  new Discord.ButtonBuilder()
    .setCustomId('nextbtn')
    .setEmoji({ id: '924719286918987816' })
    .setStyle('Secondary'),
  new Discord.ButtonBuilder()
    .setCustomId('lastbtn')
    .setEmoji({ id: '959992408651755520' })
    .setStyle('Secondary'),
])
.paginate()
```

**Additional info**
- discord.js version: ```14.0.1```
- Pagination version: ```1.3.1 ```

**Comment by acegoal07** [comment]
Could you try updating discord.js to version 14.0.2 to see if this stops the error

**Comment by acegoal07** [comment]
I've found the issue and it seems to only affect interaction paginations so I'll get the package updated as soon as possible
