### ISSUE TITLE
TypeError: Pagination is not a constructor

### ISSUE THREAD

**Issue by rctgamer3** [acegoal07/discordjs-pagination#18]
**Describe the bug**
Code on the wiki doesn't work at all. Can't even assign Pagination to a variable without setting any options.
**Error message**
``` TypeError: Pagination is not a constructor ``` 

**Sample of the code where it is used**
```JS
const Pagination = require("@acegoal07/discordjs-pagination");
new Pagination().setPortal(interaction)
    .setPageList([
        new EmbedBuilder()
            .setTitle("Embed 1")
            .setDescription("page 1"),
        new EmbedBuilder()
            .setTitle("Embed 2")
            .setDescription("page 2")
    ])
    .setButtonList([
        new ButtonBuilder()
            .setLabel(`1`)
            .setStyle("Secondary")
            .setCustomId(`1`),
        new ButtonBuilder()
            .setLabel(`2`)
            .setStyle("Secondary")
            .setCustomId(`2`)
    ])
    .paginate();
```

**Additional info**
- Package version: 1.5.8. This wasn't broken in 1.3.9

**Comment by acegoal07** [comment]
Can you just try changing the const call to the package to this 

'''Js

const { Pagination } = require("@acegoal07/discordjs-pagination");

'''

**Comment by rctgamer3** [comment]
Oh dang. I was trying to fix it in code but never noticed it was that simple. Sorry for the beginners mistake.
