### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by GlxryX** [acegoal07/discordjs-pagination#8]
**Describe the bug**
Buttons appear as null after timeout when using emojis

**Additional info**
- Package version: ``` ^1.2.6-a ```

Before timeout:
![image](https://user-images.githubusercontent.com/77895395/163686694-ba1c9f52-21cb-42f4-b053-65b3392d3593.png)
After timeout: 
![image](https://user-images.githubusercontent.com/77895395/163686700-e7d1c94a-30d5-4246-8dd7-e48fba286b9d.png)

**Comment by acegoal07** [comment]
Can you provided me with the emojis you are trying to use

**Comment by GlxryX** [comment]
previousbtn: 924719153288458271
nextbtn: 924719286918987816
lastbtn: 959992408651755520
first: 959992408433627137

**Comment by acegoal07** [comment]
The fix will be published in version 1.2.7
